import './globals.css';
import './app.css';
import type { Metadata } from 'next'
import { LayoutProvider } from '@/components';

export const metadata: Metadata = {
  title: 'Next Starter App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
